### ISSUE TITLE
chunkBy in GDC

### ISSUE THREAD

**Issue by azbukagh** [Herringway/natcmp#1]
Currently GDC's gphobos is simular to Phobos 2.066, which doesn't have `chunkBy`.
GDC is developed realy slow, so I don't think, that we can get `chunkBy` in next month. Euyp, this is not big problem, because DMD and LDC works fine, but this is only one compiler, that can be builded for cross-compiling to other platforms.

**Comment by Herringway** [comment]
Indeed. The last version to support that version of GDC was 1.2.3.

DMD 2.067.1 compatibility was recently merged, and 2.068.1 does not appear too far behind it. If you really need GDC support now, I recommend using v1.2.3 at least until GDC catches up.

**Comment by azbukagh** [comment]
Ok, 1.2.3 works fine.
